spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  datasource:
#    url: jdbc:postgresql://127.0.0.1:5432/horses
#    username: postgres
#    password: postgres

    driver-class-name: org.postgresql.Driver
#use-heroku-sql: false
server:
  port: 8080

management:
  endpoints:
    web:
      cors:
        allowed-methods: GET, OPTIONS
        allowed-headers: "*"
        allowed-origins: "*"
