spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  datasource:
#    url: jdbc:postgresql://127.0.0.1:5432/horses
#    username: postgres
#    password: postgres
    url: jdbc:postgresql://ec2-3-248-103-75.eu-west-1.compute.amazonaws.com:5432/ddve3k4uji7tfc
    username: dfdkikjrprewxt
    password:
    driver-class-name: org.postgresql.Driver
use-heroku-sql: false
server:
  port: 8080
As the stars and